services:
  app:
    image: ${RSA_IMAGE:-rsa-app:local}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rsa-app

    env_file:
      - .env

    volumes:
      - ./users.json:/app/users.json:ro
      - ./jadwal.json:/app/jadwal.json:ro

    restart: unless-stopped